# -*- coding: utf-8 -*-
"""sma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NaIkTAaKHzqsgHaFklyj6hQhsbI-7JB5
"""

import tweepy
import pandas as pd

consumer_key = 'sOhmL2iIwYRWZZv7gMrhBmrlQ'
consumer_secret = 'ctnViFefVL9oXsiZeuUqfbzFd7oTH3RNMA106HdcbbOJ13ZVZs'
access_token = '1115022912-3NnnQrmjHqDaO3MGlPnlKwQaBuyeXmkqtIN3cLm'
access_token_secret = 'A122vW5fof7etStsul6M3guOpGFNWlaFnvbjqu1VOpJK8'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)

me = api.get_user(screen_name = 'imVkohli')
me.id

user_list = ["71201743"]
follower_list = []
for user in user_list:
    followers = []
    try:
        count = api.get_user(user)
      # fetching the followers_count
        followers_count = count.followers_count
        for page in tweepy.Cursor(api.followers_ids, user_id=user).pages():
            followers.extend(page)
            print(len(followers))
            if followers_count >= 1000: #Only take first 1000 followers
                break
    except tweepy.TweepError:
        print("error")
        continue
    follower_list.append(followers)

follower_list[0]

df = pd.DataFrame(columns=['source','target']) #Empty DataFrame
df['target'] = follower_list[0] #Set the list of followers as the target column
df['source'] = 71201743 #Set my user ID as the source

import networkx as nx
G = nx.from_pandas_edgelist(df, 'source', 'target') #Turn df into graph
pos = nx.spring_layout(G) #specify layout for visual

import matplotlib.pyplot as plt
f, ax = plt.subplots(figsize=(10, 10))
plt.style.use('ggplot')
nodes = nx.draw_networkx_nodes(G, pos,
                               alpha=0.8)
nodes.set_edgecolor('k')
nx.draw_networkx_labels(G, pos, font_size=8)
nx.draw_networkx_edges(G, pos, width=1.0, alpha=0.2)

graphFile='messy.graphml'
with open(graphFile, 'wb') as fOut:
    nx.write_graphml(G, fOut)



user_list = list(df['target']) #Use the list of followers we extracted in the code above i.e. my 450 followers
for userID in user_list:
    print(userID)
    followers = []
    follower_list = []

    # fetching the user
    user = api.get_user(userID)

    # fetching the followers_count
    followers_count = user.followers_count

    try:
        for page in tweepy.Cursor(api.followers_ids, user_id=userID).pages():
            followers.extend(page)
            print(len(followers))
            if followers_count >= 5000: #Only take first 5000 followers
                break
    except tweepy.TweepError:
        print("error")
        continue
    follower_list.append(followers)
    temp = pd.DataFrame(columns=['source', 'target'])
    temp['target'] = follower_list[0]
    temp['source'] = userID
    df = df.append(temp)
    df.to_csv("networkOfFollowers.csv")

df = pd.read_csv('networkOfFollowers.csv') #Read into a df
G = nx.from_pandas_edgelist(df, 'source', 'target')

df.head()

G.number_of_nodes() #Find the total number of nodes in this graph

G_sorted = pd.DataFrame(sorted(G.degree, key=lambda x: x[1], reverse=True))
G_sorted.columns = ['nconst','degree']
G_sorted.head()

G_tmp = nx.k_core(G)

print(G_tmp)

from community import community_louvain
partition = community_louvain.best_partition(G_tmp)
#Turn partition into dataframe
partition1 = pd.DataFrame([partition]).T
partition1 = partition1.reset_index()
partition1.columns = ['names','group']

partition1.head()

G_sorted = pd.DataFrame(sorted(G_tmp.degree, key=lambda x: x[1], reverse=True))
G_sorted.columns = ['names','degree']
G_sorted.head()
dc = G_sorted

G_sorted.head()

partition1.head()

combined = pd.merge(dc,partition1, how='left', left_on="names",right_on="names")

combined.tail()

combined = combined.drop(index=combined.index[-16:])

combined.shape

G_tmp

pos = nx.spring_layout(G_tmp)
f, ax = plt.subplots(figsize=(10, 10))
plt.style.use('ggplot')
#cc = nx.betweenness_centrality(G2)
nodes = nx.draw_networkx_nodes(G_tmp, pos,
                               cmap=plt.cm.Set1,
                               node_color=combined['group'],
                               alpha=0.8)
nodes.set_edgecolor('k')
#nx.draw_networkx_labels(G_tmp, pos, font_size=8)
nx.draw_networkx_edges(G_tmp, pos, width=1.0, alpha=0.2)
plt.savefig('twitterFollowers.png')

combined = combined.rename(columns={"names": "Id"}) #I've found Gephi really likes when your node column is called 'Id'
edges = nx.to_pandas_edgelist(G_tmp)
nodes = combined['Id']
edges.to_csv("edges.csv")
combined.to_csv("nodes.csv")

graphFile='cd.graphml'
with open(graphFile, 'wb') as fOut:
    nx.write_graphml(G_tmp, fOut)

